#!/bin/bash

#Get directory containing shell script
BASEDIR=$(dirname $0)

#Set the python path to just the relevant directories
export PYTHONPATH=${BASEDIR}/src:${BASEDIR}/submodules

#Set the path to just the relevant directories
export PATH=${BASEDIR}/submodules/sonLib/bin:${BASEDIR}/submodules/cactus/bin:${BASEDIR}/submodules/jobTree/bin:${BASEDIR}/submodules/bwa/:${BASEDIR}/submodules/last/src/:${BASEDIR}/submodules/last/scripts/:${PATH}

#Run marginAlign
python ${BASEDIR}/src/margin/marginAlign.py $@