#!/bin/bash

set -e
# Any subsequent(*) commands which fail will cause the shell script to exit immediately

# Check if virtualenv has been created, and if it exists, activate it
if [ -d "./env/bin/" ]; then
	# Control will enter here if $DIRECTORY exists.
	source env/bin/activate
	# set a virtenv flag so it can be deactivated once done
	virtenv=true
fi

#Get directory containing shell script
BASEDIR=$(dirname $0)

#Set the python path to just the relevant directories
export PYTHONPATH=${BASEDIR}/src:${BASEDIR}/submodules

#Set the path to just the relevant directories
export PATH=${BASEDIR}/submodules/sonLib/bin:${BASEDIR}/submodules/jobTree/bin:${BASEDIR}/submodules/bwa/:${BASEDIR}/submodules/last/src/:${BASEDIR}/submodules/last/scripts/:${PATH}

#Run uniquifyFastq
python ${BASEDIR}/scripts/plots.py $@

# Deactivate virtualenv if it was activated
if [ $virtenv ]; then
	# deactivate virtualenv
	deactivate
fi
